# This is a basic workflow to help you get started with Actions

name: InputManualTriggerWF

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
inputs:
  number1:
    describtion: 'First Number'
    default: 0
    required: true
  number2:
    describtion: 'Second Number'
    default: 0
    required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Add 2 Numbers
        id: sum
        run: |
          echo "::set-output name=sum::${((${{ inputs.number1 }} + ${{ inputs.number2 }}))"
          echo test, and deploy your project.
